name: Deploy Preview (Reusable)

on:
  workflow_call:
    inputs:
      name:
        description: "Name of the deployment"
        required: true
        type: string
      environment:
        required: true
        type: string
      url:
        description: "URL of the deployment"
        required: true
        type: string

jobs:
  deploy:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      pull-requests: read
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: cd apps/app && bun run build
      - run: cd apps/app && npx wrangler pages deploy dist --project-name sophia-app --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
