name: Deploy Preview (Reusable)

on:
  workflow_call:
    inputs:
      name:
        description: "Name of the deployment"
        required: true
        type: string
      environment:
        required: true
        type: string
      url:
        description: "URL of the deployment"
        required: true
        type: string

jobs:
  deploy:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      pull-requests: read
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun --filter @repo/app build
      - run: bun --filter @repo/web build
      
      # Deploy React app to Cloudflare Pages
      - run: cd apps/app && npx wrangler pages deploy dist --project-name sophia-app
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      # Deploy marketing site to Cloudflare Pages
      - run: cd apps/web && npx wrangler pages deploy dist --project-name sophia-web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      # Deploy API worker
      - run: cd apps/api && npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      # Deploy Edge worker  
      - run: cd apps/edge && npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
